# Generated by Django 5.2.4 on 2025-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='no_of_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('table_booking', 'Table Booking')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('CALL_BACK_REQUESTED', 'Call Back Requested')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
